"""
Default constants for comparison tools.
"""

from ...config.config import (
    DEFAULT_SIGNIFICANCE_THRESHOLD,
    DEFAULT_SIMILARITY_THRESHOLD,
)

# Use values from central config
SIGNIFICANCE_THRESHOLD = DEFAULT_SIGNIFICANCE_THRESHOLD
SIMILARITY_THRESHOLD = DEFAULT_SIMILARITY_THRESHOLD

# Recommendation thresholds
RECOMMENDATION_CORE_RATIO_THRESHOLD = 1.5
RECOMMENDATION_MEMORY_RATIO_THRESHOLD = 1.5
RECOMMENDATION_SPILL_BYTES_THRESHOLD = 100 * 1024 * 1024  # 100MB
